Repository AndreasLrx/ecstasy, pull requests merged in 2024-10, with the labels that each got.

#162 Allow to request registry variables from the entity builder template parameters
  doc/Tutorial.md
  src/ecstasy/registry/Registry.hpp
  tests/registry/tests_Registry.cpp
Labels: enhancement, registry

#167 Fix broken links in README.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#174 Disable codecov if PR head and base are different or CODECOV_TOKEN not set
  .github/workflows/build-tests.yml
Labels: bug, ci

#175 Improved CONTRIBUTING.md with new/missing recommandations
  CONTRIBUTING.md
Labels: documentation

#177 BREAKING CHANGE: ecstasy::ResourceReference now use std::reference_wrapper
  .github/workflows/build-tests.yml
  doc/Building.md
  doc/Glossary.md
  doc/Tutorial.md
  src/ecstasy/integrations/event/EventsManager.cpp
  src/ecstasy/integrations/event/inputs/Gamepads.hpp
  src/ecstasy/integrations/event/inputs/Keyboard.hpp
  src/ecstasy/integrations/event/inputs/Mouse.hpp
  src/ecstasy/integrations/sfml/systems/PollEvents.cpp
  src/ecstasy/integrations/user_action/PollActions.hpp
  src/ecstasy/integrations/user_action/Users.cpp
  src/ecstasy/integrations/user_action/Users.hpp
  src/ecstasy/query/concepts/Queryable.hpp
  src/ecstasy/registry/Registry.cpp
  src/ecstasy/registry/Registry.hpp
  src/ecstasy/registry/concepts/queryable_type.hpp
  src/ecstasy/resources/CMakeLists.txt
  src/ecstasy/resources/IResource.hpp
  src/ecstasy/resources/ObjectWrapper.hpp
  src/ecstasy/resources/Resource.hpp
  src/ecstasy/resources/entity/Entities.hpp
  src/ecstasy/resources/include.hpp
  src/ecstasy/thread/LockableView.hpp
  tests/registry/tests_DeletionStack.cpp
  tests/registry/tests_Registry.cpp
Labels: bug, BREAKING CHANGE

#178 Add missing tutorial about resources usage
  doc/Tutorial.md
Labels: documentation
